import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Inter } from 'next/font/google';
import AppTheme from '@/theme/AppTheme';
import AppNavBar from "@/components/AppNavBar/AppNavBar";

const inter = Inter({
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable} suppressHydrationWarning>
        <AppRouterCacheProvider>
          <AppTheme>
              <AppNavBar />
                {children}
          </AppTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
